version: '3.8'

services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: akshare-notice-worker
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: akshare-notice-web
    ports:
      - "8083:8083"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    depends_on:
      - worker
